### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by pujie1216** [Xposed-Modules-Repo/com.mhook.dialog.new#1]
http代理这个功能可以单独出一个app吗？网络调试需要频繁开关，可以的话希望能在磁贴栏添加一个快速开关 XD

**Comment by serifer** [comment]
需要频繁切换的话，建议直接通过adb命令快捷设置代理，会更方便一点

**Comment by pujie1216** [comment]
电脑不可能一直在身边啊，而且点一下开关总比敲命令快吧，还有新问题，某些链接用模块代理不到，但是换成系统的WIFI代理却没问题，还是建议单独做app，走VPN，类似postern那样

**Comment by serifer** [comment]
就是你想要一个可以快捷开关的代理，不管是wifi代理，还是vpn代理，还是这个模块的代理方式

**Comment by pujie1216** [comment]
是这样的,类似iOS小火箭的下拉通知栏快捷开关

**Comment by serifer** [comment]
已支持  
https://github.com/Xposed-Modules-Repo/com.mhook.dialog.new/releases/tag/1-22.12_beta1
