### ISSUE TITLE
English please 

### ISSUE THREAD

**Issue by ammlr** [Xposed-Modules-Repo/com.mhook.dialog.new#3]
this is a very awesome app. please add english . we really don't understand your language

**Comment by serifer** [comment]
Do you have people abroad using it too?

**Comment by serifer** [comment]
I don't know much English, so if we want to support English, either we should use machine translation (such as Google Translate, DeepL translation), or I should post the string resources to github, so that we can jointly translate and correct errors, or a combination of both options.

**Comment by serifer** [comment]
@ammlr https://install.appcenter.ms/users/serifer/apps/dialbox/distribution_groups/beta

English is supported!

**Comment by serifer** [comment]
If you can, you can first try the app for testing: https://apkpure.com/cn/store/apps/details?id=ru.andr7e.deviceinfohw

**Comment by serifer** [comment]
ig, tiktok and other applications have a strict detection mechanism on whether the device is new or not, to prevent cheating, currently I only do interception in the java layer, if it gets the device information in the so layer, it will not work
