### ISSUE TITLE
希望可以把旧对话框取消的（启动时禁用网络）功能加上

### ISSUE THREAD

**Issue by wzgrx** [Xposed-Modules-Repo/com.mhook.dialog.new#6]
启动时禁用网络
设置禁用链接中关键词
设置欲禁用的域名或ip或请求链接中的关键词,多个用英文空格隔开，为空则禁用全部

这个可以屏蔽虎牙的p2p上传流量，还是挺好用的

具体版本:对话框取消 Beta版 0.1.1
其他旧版本也有

**Comment by serifer** [comment]
我以为没用呢，下一版本加上

**Comment by serifer** [comment]
已添加：下载地址：https://install.appcenter.ms/users/serifer/apps/Dialbox
